name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Delete Docker Image and Containers
        run: sudo docker rm -f dweb

      - name: Pull Docker Image from Docker Hub
        run: sudo docker pull jhshin29/songdo:latest

      - name: Execute Docker Container
        run: sudo docker run -d -p 80:3000 --name jh jhshin29/songdo:latest
